name: Lint

on:
  pull_request:
    branches: [ main ]

jobs:
  check-md:
    name: Check that all links exist
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Cache
        uses: actions/cache@v2.1.4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - uses: actions/setup-node@v2
        with:
          node-version: 12
      - run: npm i check-md

      - run: echo "::add-matcher::.github/workflow-support/check-md-matcher.json"
      - run: node .github/workflow-support/check-md.js
      - run: echo "::remove-matcher owner=check-md::"
        if: success() || failure()

