name: Lint

on:
  pull_request:
    branches: [ main ]

jobs:
  htmlproofer:
    name: Run htmlproofer
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7.x
          bundler-cache: true
      - run: bundle install
      - run: bundle exec jekyll build
      - name: Check for broken links
        run: bundle exec htmlproofer --assume-extension ./_site